name: learn-2021


on:
  push:
    branc   hes: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: instal NodeJs
      uses: action/setup-node@v2-beta
      with:
       node-version: 12  
    - name: Install surge
      run:  npm install -g surge
    - name: Run surge
      run: surge./learnbilal.surge.sh --token ${{secrets.TOKEN}}
      
